
# Undertow does not support static resource loading (like js img), Use Tomcat instead if you want
# Undertow不支持静态资源加载(例如 js img), 需要的话改用Tomcat

## tomcat
server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    ## TODO [重要]指定tomcat的basedir, 用于临时文件, 该目录需要创建. 避免运行十天出现The temporary upload location...的异常
    basedir: ./tmp
    max-threads: 200
    accept-count: 200
    max-connections: 2000
    min-spare-threads: 10
    max-http-post-size: 10485760
#  compression:
#    enabled: true
#    mime-types: application/json,application/xml,text/html,text/xml,text/plain
#    min-response-size: 2048

## undertow
#server:
#  port: 8080
#  address: 0.0.0.0
#  undertow:
#    io-threads: 4
#    worker-threads: 256
#    buffer-size: 4096
#    direct-buffers: true
#    max-http-post-size: 10485760
