
#####################################################################

spring:
  application:
    name: ${app.id}
  ## default profile
  profiles:
    active: win
  ## Jackson config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  ## i18n message
  messages:
    basename: msg/messages,msg/errors
    encoding: UTF-8
  ## MVC config for web app
  mvc:
    view:
      prefix: /
      suffix: .html
  ## Datasource 1: H2 (Do not exclude DataSourceAutoConfiguration!)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2db1
    username: sa
    password: sa
    schema: classpath:config/demo/mybatis/h2init/schema.sql
    data: classpath:config/demo/mybatis/h2init/data.sql
    initialization-mode: always
  ## Datasource 2: Mysql (Do not exclude DataSourceAutoConfiguration!)
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: test
#    password: test
#    initial-size: 5
#    min-idle: 5
#    max-idle: 50
#    max-active: 50
#    max-wait: 5000
#    validation-query: SELECT 1 FROM DUAL
  ## Datasource 3: Oracle (Do not exclude DataSourceAutoConfiguration!)
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#    username: sviolet
#    password: sviolet
#    initial-size: 5
#    min-idle: 5
#    max-idle: 50
#    max-active: 50
#    max-wait: 5000
#    validation-query: SELECT 1 FROM DUAL
  ## Datasource 4: Oracle with org.apache.tomcat:tomcat-jdbc (Do not exclude DataSourceAutoConfiguration!)
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#    username: sviolet
#    password: sviolet
#    tomcat:
#      initial-size: 5
#      min-idle: 5
#      max-idle: 50
#      max-active: 50
#      max-wait: 10000
#      time-between-eviction-runs-millis: 30000
#      min-evictable-idle-time-millis: 1800000
#      validation-query: select 1 from dual
#      test-while-idle: true
#      test-on-borrow: true
  ## H2 Console For Test, Set 'JDBC URL' to 'jdbc:h2:mem:h2db1' when login
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
  ## Force Http Encoding
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
#      force: true
  cloud:
    ## Sentinel client, https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel, DefaultLog: ${user.home}/logs/csp
    sentinel:
      enabled: true
      transport:
        ## dashboard address
        dashboard: localhost:60000
        ## client will listen this port to receive control command, Port conflicts will automatically avoid
        port: 60001
        ## Used to let the dashboard find itself. For Linux environment, please set the host name and host IP if you want to get the client-ip automatically.
#        client-ip: 127.0.0.1
#      metric:
#        file-single-size: 52428800
#        file-total-count: 6
#      log:
#        dir: logs/
  ## Spring Boot Admin config (Config in client)
#  boot:
#    admin:
#      client:
#        ## The url of admin server
#        url: http://localhost:8080

#####################################################################

## Mybatis config
mybatis:
  mapper-locations: classpath:config/demo/mybatis/mapper/*.xml
  config-location: classpath:config/demo/mybatis/mybatis-config.xml

## Mybatis PageHelper (com.github.pagehelper:pagehelper-spring-boot-starter)
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: h2
#  helper-dialect: oracle
#  helper-dialect: mysql

#####################################################################

## Actuator config, For Prometheus / Spring Boot Admin, Config in client
## Endpoints: http://localhost:8080/actuator/{health,prometheus,...}
management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 1m
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: shutdown
  endpoint:
    health:
      show-details: always
    beans:
      cache:
        time-to-live: 10s
    shutdown:
      enabled: true

#####################################################################

## Slate config
slate:
  common:
    servlet-context-listener-enabled: true
    ez-sentinel:
      rule-data: classpath:config/demo/sentinel/rules.json
#  httpclient:
#    enabled: true
#    apollo-support: true
#  httpclients:
#    default:
#      hosts: http://127.0.0.1:8080,http://127.0.0.1:8081
#      verbose-log: true

#####################################################################

## Config for rocketmq-spring-boot-starter, optional
## https://github.com/apache/rocketmq-spring
#rocketmq:
#  name-server: host1:9876;host2:9876
#  producer:
#    group: starter-producer
#    send-message-timeout: 30000
#    compress-message-body-threshold: 4096
#    max-message-size: 65535
#    retry-times-when-send-async-failed: 0
#    retry-next-server: true
#    retry-times-when-send-failed: 2

#####################################################################

# Other configs
debug: false

#####################################################################

# 配置文件优先级: (很奇怪如果放了config/application.yaml文件, IDEA会识别不了yaml, 导致编辑无提示)
# 启动参数
# ./config/application.properties
# ./config/application.yaml
# ./application.properties
# ./application.yaml
# classpath:config/application.properties
# classpath:config/application.yaml
# classpath:application.properties
# classpath:application.yaml
# @PropertySource或PropertySourcesPlaceholderConfigurer加载的配置
